import type { LlmClient } from "./LlmClient";

/**
 * Deterministic mock used when no ANTHROPIC_API_KEY is set (config.useMockLlm)
 * and in unit/contract tests. It doesn't try to be "smart" about the prompt —
 * it inspects the document IDs embedded in the prompt (formatted as
 * "[DOCUMENT id=<uuid>") so the returned findings reference real,
 * caller-supplied document IDs and pass sourceDocumentIds validation just
 * like a real model response would.
 */
export class MockLlmClient implements LlmClient {
  async complete(_systemPrompt: string, userPrompt: string): Promise<string> {
    const ids = Array.from(userPrompt.matchAll(/\[DOCUMENT id=([a-zA-Z0-9-]+)/g)).map((m) => m[1]);
    const uniqueIds = Array.from(new Set(ids));

    const perDocument = uniqueIds.map((documentId) => ({
      documentId,
      summary: `Mock summary of document ${documentId}. (No ANTHROPIC_API_KEY configured — set one in .env to use the real model.)`,
      findings: [
        {
          title: "Mock finding",
          category: "extraction" as const,
          extractedFacts: ["This is a placeholder fact generated by the mock LLM client."],
          aiInterpretation: "This is a placeholder interpretation generated by the mock LLM client.",
          sourceDocumentIds: [documentId],
          confidence: "low" as const,
        },
      ],
    }));

    const synthesis = {
      summary:
        uniqueIds.length > 1
          ? `Mock cross-document synthesis across ${uniqueIds.length} documents.`
          : "Mock synthesis (only one document was provided).",
      findings:
        uniqueIds.length > 0
          ? [
              {
                title: "Mock cross-document finding",
                category: "comparison" as const,
                extractedFacts: ["Placeholder cross-document fact."],
                aiInterpretation: "Placeholder cross-document interpretation.",
                sourceDocumentIds: uniqueIds,
                confidence: "low" as const,
              },
            ]
          : [],
    };

    return JSON.stringify({ perDocument, synthesis });
  }
}
