/**
 * Content-aware building blocks for MockLlmClient. Kept separate from
 * MockLlmClient itself so the "no API key" fallback stays easy to read: it
 * recognizes a handful of document shapes used by sample-documents/ (loan
 * application / identity verification / bank statement, and purchase order /
 * vendor invoice) and produces findings that actually reflect what's in the
 * text — including cross-document discrepancy detection — while still
 * falling back to a generic placeholder finding for anything it doesn't
 * recognize, so arbitrary uploads never break.
 */

export interface MockDocument {
  documentId: string;
  fileName: string;
  fileType: string;
  text: string;
}

export interface MockFinding {
  title: string;
  category: "comparison" | "discrepancy" | "summary" | "extraction" | "other";
  extractedFacts: string[];
  aiInterpretation: string;
  sourceDocumentIds: string[];
  confidence: "low" | "medium" | "high";
}

export interface MockPerDocument {
  documentId: string;
  summary: string;
  findings: MockFinding[];
}

export interface MockSynthesis {
  summary: string;
  findings: MockFinding[];
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Reads a "Label: value" line, anchored to the start of a line so "Total:" doesn't match inside "Subtotal:". */
function extractField(text: string, label: string): string | undefined {
  const match = text.match(new RegExp(`^\\s*${escapeRegex(label)}:\\s*(.+)$`, "im"));
  return match?.[1]?.trim();
}

function findLineContaining(text: string, needle: string): string | undefined {
  return text.split("\n").find((line) => line.toLowerCase().includes(needle.toLowerCase()))?.trim();
}

function normalizeForCompare(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]/g, "");
}

function parseAmount(s: string): number | undefined {
  const match = s.replace(/,/g, "").match(/-?\d+(\.\d+)?/);
  return match ? parseFloat(match[0]) : undefined;
}

/** Parses the header + rows out of the compact "field, field, ...\nval, val, ..." CSV text produced by CsvExtractor. */
function parseCsvText(text: string): { headers: string[]; rows: string[][] } {
  const lines = text.split("\n").filter((l) => l.trim().length > 0);
  const headers = (lines[0] ?? "").split(",").map((h) => h.trim());
  const rows = lines.slice(1).map((line) => line.split(",").map((cell) => cell.trim()));
  return { headers, rows };
}

const GENERIC_FINDING: Omit<MockFinding, "sourceDocumentIds"> = {
  title: "Mock finding",
  category: "extraction",
  extractedFacts: ["This is a placeholder fact generated by the mock LLM client."],
  aiInterpretation: "This is a placeholder interpretation generated by the mock LLM client.",
  confidence: "low",
};

function analyzeDocument(doc: MockDocument): { summary: string; findings: MockFinding[] } {
  if (/PERSONAL LOAN APPLICATION/i.test(doc.text)) {
    const name = extractField(doc.text, "Applicant Name");
    const employer = extractField(doc.text, "Employer");
    const income = extractField(doc.text, "Monthly Gross Income");
    const amount = extractField(doc.text, "Amount");
    return {
      summary: `Personal loan application${name ? ` from ${name}` : ""}${amount ? `, requesting ${amount}` : ""}.`,
      findings: [
        {
          title: "Applicant and loan details extracted",
          category: "extraction",
          extractedFacts: [
            name && `Applicant name: "${name}"`,
            employer && `Employer: "${employer}"`,
            income && `Declared monthly gross income: "${income}"`,
            amount && `Requested loan amount: "${amount}"`,
          ].filter((f): f is string => Boolean(f)),
          aiInterpretation:
            "Key identifying and financial details captured from the loan application, for cross-referencing against any other submitted documents.",
          sourceDocumentIds: [doc.documentId],
          confidence: "high",
        },
      ],
    };
  }

  if (/IDENTITY VERIFICATION FORM/i.test(doc.text)) {
    const name = extractField(doc.text, "Full Name");
    const pan = extractField(doc.text, "PAN");
    const employer = extractField(doc.text, "Employer on File");
    return {
      summary: `Identity verification record${name ? ` for ${name}` : ""}.`,
      findings: [
        {
          title: "Identity details extracted",
          category: "extraction",
          extractedFacts: [
            name && `Full name on file: "${name}"`,
            pan && `PAN: "${pan}"`,
            employer && `Employer on file: "${employer}"`,
          ].filter((f): f is string => Boolean(f)),
          aiInterpretation: "Verified identity fields captured for cross-referencing against other submitted documents.",
          sourceDocumentIds: [doc.documentId],
          confidence: "high",
        },
      ],
    };
  }

  if (/PURCHASE ORDER/i.test(doc.text)) {
    const poNumber = extractField(doc.text, "PO Number");
    const vendor = extractField(doc.text, "Vendor");
    const total = extractField(doc.text, "Total");
    return {
      summary: `Purchase order${poNumber ? ` ${poNumber}` : ""}${vendor ? ` issued to ${vendor}` : ""}.`,
      findings: [
        {
          title: "Purchase order details extracted",
          category: "extraction",
          extractedFacts: [
            poNumber && `PO number: "${poNumber}"`,
            vendor && `Vendor: "${vendor}"`,
            total && `Total: "${total}"`,
          ].filter((f): f is string => Boolean(f)),
          aiInterpretation: "Order-level details captured for reconciliation against the corresponding vendor invoice, if provided.",
          sourceDocumentIds: [doc.documentId],
          confidence: "high",
        },
      ],
    };
  }

  if (/VENDOR INVOICE/i.test(doc.text)) {
    const invoiceNumber = extractField(doc.text, "Invoice Number");
    const poReference = extractField(doc.text, "PO Reference");
    const total = extractField(doc.text, "Total");
    return {
      summary: `Vendor invoice${invoiceNumber ? ` ${invoiceNumber}` : ""}${poReference ? `, referencing ${poReference}` : ""}.`,
      findings: [
        {
          title: "Invoice details extracted",
          category: "extraction",
          extractedFacts: [
            invoiceNumber && `Invoice number: "${invoiceNumber}"`,
            poReference && `PO reference: "${poReference}"`,
            total && `Total: "${total}"`,
          ].filter((f): f is string => Boolean(f)),
          aiInterpretation: "Billed amount captured for reconciliation against the referenced purchase order, if provided.",
          sourceDocumentIds: [doc.documentId],
          confidence: "high",
        },
      ],
    };
  }

  if (doc.fileType === "csv" && /balance/i.test(doc.text)) {
    const { headers, rows } = parseCsvText(doc.text);
    const descIdx = headers.findIndex((h) => /description/i.test(h));
    const salaryRow = descIdx >= 0 ? rows.find((r) => /salary/i.test(r[descIdx] ?? "")) : undefined;
    const salaryLine = salaryRow ? salaryRow.join(", ") : undefined;
    return {
      summary: "Bank statement covering a mix of debits and credits.",
      findings: [
        {
          title: salaryLine ? "Salary credit identified" : "No salary credit found",
          category: "extraction",
          extractedFacts: salaryLine ? [`Transaction row: "${salaryLine}"`] : ["No transaction labeled as a salary credit was found."],
          aiInterpretation: salaryLine
            ? "This credit is a candidate for corroborating a declared employer/income figure stated elsewhere."
            : "Without a salary-labeled transaction, declared income cannot be corroborated from this statement alone.",
          sourceDocumentIds: [doc.documentId],
          confidence: salaryLine ? "medium" : "low",
        },
      ],
    };
  }

  return {
    summary: `Mock summary of document ${doc.fileName || doc.documentId}. (No ANTHROPIC_API_KEY configured — set one in .env to use the real model.)`,
    findings: [{ ...GENERIC_FINDING, sourceDocumentIds: [doc.documentId] }],
  };
}

function buildLoanIdentityBankFindings(
  loanDoc: MockDocument | undefined,
  idDoc: MockDocument | undefined,
  bankDoc: MockDocument | undefined
): MockFinding[] {
  const findings: MockFinding[] = [];

  if (loanDoc && idDoc) {
    const loanName = extractField(loanDoc.text, "Applicant Name");
    const idName = extractField(idDoc.text, "Full Name");
    if (loanName && idName) {
      const match = normalizeForCompare(loanName) === normalizeForCompare(idName);
      findings.push({
        title: match
          ? "Applicant name is consistent across documents"
          : "Applicant name mismatch between loan application and identity verification",
        category: match ? "comparison" : "discrepancy",
        extractedFacts: [`Loan application name: "${loanName}"`, `Identity verification name: "${idName}"`],
        aiInterpretation: match
          ? "The applicant's name matches exactly between the loan application and the identity verification record."
          : "The name on file differs between the loan application and the identity verification record. This may be a benign abbreviation, but should be confirmed with the applicant before proceeding.",
        sourceDocumentIds: [loanDoc.documentId, idDoc.documentId],
        confidence: match ? "high" : "medium",
      });
    }
  }

  if (loanDoc && bankDoc) {
    const employer = extractField(loanDoc.text, "Employer");
    const income = extractField(loanDoc.text, "Monthly Gross Income");
    const { headers, rows } = parseCsvText(bankDoc.text);
    const descIdx = headers.findIndex((h) => /description/i.test(h));
    const creditIdx = headers.findIndex((h) => /credit/i.test(h));
    const salaryRow = descIdx >= 0 ? rows.find((r) => /salary/i.test(r[descIdx] ?? "")) : undefined;
    const salaryDescription = salaryRow && descIdx >= 0 ? salaryRow[descIdx] : undefined;

    if (employer && salaryDescription) {
      const employerMatches = normalizeForCompare(salaryDescription).includes(normalizeForCompare(employer));
      findings.push({
        title: employerMatches
          ? "Salary credit corroborates declared employer"
          : "No bank transaction corroborates declared employer",
        category: employerMatches ? "comparison" : "discrepancy",
        extractedFacts: [`Declared employer: "${employer}"`, `Bank transaction description: "${salaryDescription}"`],
        aiInterpretation: employerMatches
          ? "A salary credit transaction referencing the declared employer was found in the bank statement, corroborating the applicant's stated employment."
          : "No transaction in the bank statement clearly references the declared employer — worth a closer look.",
        sourceDocumentIds: [loanDoc.documentId, bankDoc.documentId],
        confidence: employerMatches ? "high" : "low",
      });
    }

    if (income && salaryRow && creditIdx >= 0) {
      const incomeAmount = parseAmount(income);
      const creditAmount = parseAmount(salaryRow[creditIdx] ?? "");
      if (incomeAmount !== undefined && creditAmount !== undefined) {
        const amountMatches = Math.abs(incomeAmount - creditAmount) < 1;
        findings.push({
          title: amountMatches ? "Salary credit amount matches declared income" : "Salary credit amount differs from declared income",
          category: amountMatches ? "comparison" : "discrepancy",
          extractedFacts: [
            `Declared monthly gross income: "${income}"`,
            `Bank salary credit amount: ${creditAmount.toFixed(2)}`,
          ],
          aiInterpretation: amountMatches
            ? "The declared monthly income is corroborated by a matching salary credit in the bank statement."
            : "The salary credit amount in the bank statement does not match the declared income figure — worth flagging for review.",
          sourceDocumentIds: [loanDoc.documentId, bankDoc.documentId],
          confidence: amountMatches ? "high" : "medium",
        });
      }
    }
  }

  return findings;
}

function buildPurchaseOrderInvoiceFindings(
  poDoc: MockDocument | undefined,
  invDoc: MockDocument | undefined
): MockFinding[] {
  if (!poDoc || !invDoc) return [];

  const poTotal = extractField(poDoc.text, "Total");
  const invTotal = extractField(invDoc.text, "Total");
  if (!poTotal || !invTotal) return [];

  const poAmount = parseAmount(poTotal);
  const invAmount = parseAmount(invTotal);
  const totalsMatch = poAmount !== undefined && invAmount !== undefined && Math.abs(poAmount - invAmount) < 1;

  const facts = [`Purchase order total: "${poTotal}"`, `Vendor invoice total: "${invTotal}"`];

  // Best-effort: surface one differing line item, if we can find one with matching wording.
  for (const label of ["Monitor Arm", "Standing Desk", "Chair"]) {
    const poLine = findLineContaining(poDoc.text, label);
    const invLine = findLineContaining(invDoc.text, label);
    if (poLine && invLine && poLine !== invLine) {
      facts.push(`PO line item: "${poLine}"`, `Invoice line item: "${invLine}"`);
      break;
    }
  }

  return [
    {
      title: totalsMatch ? "Invoice total matches purchase order" : "Invoice total does not match purchase order",
      category: totalsMatch ? "comparison" : "discrepancy",
      extractedFacts: facts,
      aiInterpretation: totalsMatch
        ? "The billed amount matches what was ordered."
        : "The vendor invoiced a different amount than what was ordered, likely due to a quantity discrepancy on one of the line items. Recommend reconciling before payment.",
      sourceDocumentIds: [poDoc.documentId, invDoc.documentId],
      confidence: totalsMatch ? "high" : "medium",
    },
  ];
}

export function buildMockAnalysis(docs: MockDocument[]): { perDocument: MockPerDocument[]; synthesis: MockSynthesis } {
  const perDocument: MockPerDocument[] = docs.map((doc) => {
    const { summary, findings } = analyzeDocument(doc);
    return { documentId: doc.documentId, summary, findings };
  });

  const loanDoc = docs.find((d) => /PERSONAL LOAN APPLICATION/i.test(d.text));
  const idDoc = docs.find((d) => /IDENTITY VERIFICATION FORM/i.test(d.text));
  const bankDoc = docs.find((d) => d.fileType === "csv" && /balance/i.test(d.text));
  const poDoc = docs.find((d) => /PURCHASE ORDER/i.test(d.text));
  const invDoc = docs.find((d) => /VENDOR INVOICE/i.test(d.text));

  const recognizedFindings = [
    ...buildLoanIdentityBankFindings(loanDoc, idDoc, bankDoc),
    ...buildPurchaseOrderInvoiceFindings(poDoc, invDoc),
  ];

  if (recognizedFindings.length > 0) {
    const sourceIds = Array.from(new Set(recognizedFindings.flatMap((f) => f.sourceDocumentIds)));
    const hasDiscrepancy = recognizedFindings.some((f) => f.category === "discrepancy");
    return {
      perDocument,
      synthesis: {
        summary: hasDiscrepancy
          ? `Cross-document synthesis across ${sourceIds.length} documents found at least one discrepancy worth reviewing — see findings below.`
          : `Cross-document synthesis across ${sourceIds.length} documents found the submitted details consistent with each other.`,
        findings: recognizedFindings,
      },
    };
  }

  const uniqueIds = docs.map((d) => d.documentId);
  return {
    perDocument,
    synthesis: {
      summary:
        uniqueIds.length > 1
          ? `Mock cross-document synthesis across ${uniqueIds.length} documents.`
          : "Mock synthesis (only one document was provided).",
      findings:
        uniqueIds.length > 0
          ? [
              {
                title: "Mock cross-document finding",
                category: "comparison",
                extractedFacts: ["Placeholder cross-document fact."],
                aiInterpretation: "Placeholder cross-document interpretation.",
                sourceDocumentIds: uniqueIds,
                confidence: "low",
              },
            ]
          : [],
    },
  };
}
